name: CI/CD for Sales ETL DataOps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit Tests
        run: |
          echo "✅ Running ETL pipeline test"
          python main.py

      - name: Build Docker Image
        run: |
          # Tag image with both 'latest' and Git commit SHA
          IMAGE_TAG=latest
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t sales-etl-dataops:$IMAGE_TAG -t sales-etl-dataops:$COMMIT_SHA .

      - name: Login to Docker Hub and push image
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker tag sales-etl-dataops:latest $DOCKER_USERNAME/sales-etl-dataops:latest
          docker push $DOCKER_USERNAME/sales-etl-dataops:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      
       -name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Pulling latest Docker image..."
            docker pull $DOCKER_USERNAME/sales-etl-dataops:latest

            echo "Stopping old containers..."
            docker-compose -f /home/ubuntu/sales-etl-dataops/docker-compose.yaml down

            echo "Starting new containers..."
            docker-compose -f /home/ubuntu/sales-etl-dataops/docker-compose.yaml up -d

            echo "✅ Deployment complete!"
